### ISSUE TITLE
Overview papercuts

### ISSUE THREAD

**Issue by victorporof** [mozilla/tofino#1181]
- [ ] Consider making the overview a content page #912 
- [ ] Ability to rearrange tabs in Overview #954 
- [ ] Ability to close tabs in Overview #955 
- [ ] Ability to bring up a right-click menu with options in Overview #956
- [ ] Overview becomes tab control hub #957
- [ ] Don't Hide Address Bar on Overview #1085 
- [ ] Consider Moving Overview Icon to Tab Bar #1157
- [ ] Fix Overview Page's metadata parsing #1179
