### ISSUE TITLE
Implement context menus

### ISSUE THREAD

**Issue by victorporof** [mozilla/tofino#1182]
- [x] Context Menu: Links #347 
- [x] Context Menu: Selected Text #348 
- [x] Context Menu: Standard #349 
- [x] Context Menu: URL Bar #666

**Comment by jsantell** [comment]
All context menus are implemented that are necessary to be implemented for v1
