### ISSUE TITLE
Make tofino work with brave-electron

### ISSUE THREAD

**Issue by joewalker** [mozilla/tofino#1545]
Includes:

* [ ] [Tab history is broken in brave-electron](#1229)
* [ ] [New tabs opened from content don't work in brave-electron](#1228)
* [ ] [brave-electron doesn't allow the UI to access the UA service](#1227)
* [ ] [Registering the tofino:// protocol crashes brave-electron](#1226)
