### ISSUE TITLE
[meta] Make a "co-bookmarking" demo on the same desktop

### ISSUE THREAD

**Issue by bgrins** [mozilla/tofino#474]
Idea: we should be able to run two instances of the frontend that connect to a single UA process, and make clicking the bookmark star in one of the frontends also change the bookmark state in the other.

In order to do this:

- [x] Allow connecting to an already running service: https://github.com/mozilla/tofino/pull/448
- [ ] Split out the UA service into a different process: https://github.com/mozilla/tofino/pull/499
- [ ] Remove some of the "glue" that's sticking together the main process and the storage
- [ ] Try to make a screencast of it and see if we are missing anything from this list

**Comment by Mossop** [comment]
We also need #499

**Comment by Mossop** [comment]
Actually, #499 is all we need to get bookmark stars working!

**Comment by victorporof** [comment]
Looks like this is done. Closing. Reopen if I'm wrong.
